@extends('layouts.app')
@section('title','Projects')
@section('content')
<section class="projects-section py-5">
  <div class="projects-section-content container">
    <h2 class="mb-4">Projects</h2>

    <div class="row gx-4 gy-4">
      <div class="col-md-6 col-lg-4">
        <div class="card h-100 shadow-sm">
          <img class="card-img-top" src="{{ asset('assets/template/assets/profile.png') }}" alt="ShopBangla">
          <div class="card-body">
            <h5 class="card-title">ShopBangla — E-commerce</h5>
            <p class="card-text">
              Multi-tenant Laravel store for SMEs in Bangladesh. Catalog, cart, orders, invoices,
              bKash/Nagad stubs, admin RBAC, server-side pagination.
            </p>
            <ul class="small mb-0">
              <li>Laravel 11/12, MySQL 8, Redis cache</li>
              <li>Queues via Horizon for email/invoice jobs</li>
              <li>CI/CD GitHub Actions → Ubuntu/Nginx</li>
            </ul>
          </div>
          <div class="card-footer bg-white">
            <span class="badge text-bg-primary">Laravel</span>
            <span class="badge text-bg-secondary">MySQL</span>
            <span class="badge text-bg-info">Bootstrap</span>
          </div>
        </div>
      </div>

      <div class="col-md-6 col-lg-4">
        <div class="card h-100 shadow-sm">
          <img class="card-img-top" src="{{ asset('assets/template/assets/profile.png') }}" alt="MedServe BD">
          <div class="card-body">
            <h5 class="card-title">MedServe BD — Clinic MIS</h5>
            <p class="card-text">
              Appointments, EMR, VAT invoices. Roles for receptionist, doctor, admin.
              Audit logs, soft delete with restore, PDF receipts.
            </p>
            <ul class="small mb-0">
              <li>Laravel API + Vue 3 SPA</li>
              <li>Policies, gates, request validation</li>
              <li>Covering indexes for patient lookups</li>
            </ul>
          </div>
          <div class="card-footer bg-white">
            <span class="badge text-bg-primary">Laravel</span>
            <span class="badge text-bg-warning">Vue 3</span>
            <span class="badge text-bg-secondary">Redis</span>
          </div>
        </div>
      </div>

      <div class="col-md-6 col-lg-4">
        <div class="card h-100 shadow-sm">
          <img class="card-img-top" src="{{ asset('assets/template/assets/profile.png') }}" alt="EduTrack">
          <div class="card-body">
            <h5 class="card-title">EduTrack — LMS Lite</h5>
            <p class="card-text">
              Courses, lessons, quizzes, progress tracking. Certificates generated by queued jobs.
              Teacher/student dashboards with Blade components.
            </p>
            <ul class="small mb-0">
              <li>Laravel 10+, Blade components</li>
              <li>DOMPDF for PDFs, storage links</li>
              <li>Role/permission guards</li>
            </ul>
          </div>
          <div class="card-footer bg-white">
            <span class="badge text-bg-primary">Laravel</span>
            <span class="badge text-bg-dark">Policies</span>
            <span class="badge text-bg-secondary">Queues</span>
          </div>
        </div>
      </div>
    </div>

    <h3 class="mt-5 mb-3">Highlights</h3>
    <ul class="list-group">
      <li class="list-group-item">Reduced slow queries by 70% with composite indexes and caching.</li>
      <li class="list-group-item">Feature tests for checkout, auth, invoice; CI enforced before deploy.</li>
      <li class="list-group-item">Dockerized local dev; reproducible builds across the team.</li>
    </ul>
  </div>
</section>
@endsection
